// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9b2GdZWeBknWrzJ06gaOpd4Ga11ZbXC8',
    appId: '1:965193620047:web:02d140dd831136180ee83a',
    messagingSenderId: '965193620047',
    projectId: 'bookswap-db3fd2',
    authDomain: 'bookswap-db3fd.firebaseapp.com',
    storageBucket: 'bookswap-db3fd.firebasestorage.app',
    measurementId: 'G-H2DWCJSHNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsE832AH1qzv1W-A7zcdMSrgaP8tEhx5A',
    appId: '1:345650039823:android:5edfd37facadb02749677a',
    messagingSenderId: '345650039823',
    projectId: 'book-swap-e64322',
    storageBucket: 'book-swap-e6432.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpx-7uqaPlmN1lJDuw0mV1FgCwacDwA1g',
    appId: '1:345650039823:ios:039579204055bd3c49677a',
    messagingSenderId: '345650039823',
    projectId: 'book-swap-e64322',
    storageBucket: 'book-swap-e6432.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );
}
